import { VerticalBox, Button } from "std-widgets.slint";

export global Logic {
    callback send-to-osc(string);
    callback do-recording(string);
}

export component AppWindow inherits Window {
    title: "ilo kalama-tawa-sitelen tan kulupu Melondog";
    background: #202020;
    default-font-size: 16px;
    in-out property <string> stt-text;
    in-out property <string> status-text;

    GridLayout {
        padding: 20px;
        spacing: 10px;
        Row {
            Text { 
                text: "ilo kalama tawa sitelen tan MelonSTT.  o kepeken e leko anpa; ona li open kute."; 
                colspan: 3; 
                color: white; 
            }
        }
        Row { Text { text: " "; }}
        Row {
            Button { text: "tenpo 3"; clicked => { Logic.do-recording("3"); }}
            Button { text: "tenpo 6"; clicked => { Logic.do-recording("6"); }}
            Button { text: "tenpo 9"; clicked => { Logic.do-recording("9"); }}
        }
        Row {
            Text { 
                text: root.stt-text;
                color: lightblue;
                wrap: word-wrap;
                width: 400px;
                height: 100px;
                colspan: 3;
                vertical-alignment: center;
            }
        }
        Row {
            Button {
                text: "o kepeken tawa pana.";
                colspan: 3;
                clicked => { Logic.send-to-osc(root.stt-text); }
            }
        }
        Row {
            Text { text: ""; }
        }
        Row {
            Text { 
                text: "sona: " + root.status-text; 
                colspan: 3; 
                wrap: word-wrap;
                width: 400px;
                color: white;
                font-size: 12px;
                horizontal-alignment: left;
            }
        }
        Row { Text { text: " "; }}
        Row { Text { 
            text: "MelonSTT tan mama Jawakun en kijetesantakalu Sepikun.";
            colspan: 3;
            color: gray;
            font-size: 8px;
        }}
    }
}
